spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user-db
#    url: jdbc:postgresql://auth-db:5432/user-db
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 #Настройки пула соединений (HikariCP — дефолтный пул в Spring Boot).
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Показывать SQL-запросы в логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret: PCiMTSVb+H8qnA4g4ZgfQoTMJbAbPrhxK3zCzkK6j0Q=
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG