spring:
  cloud:
    gateway:
      discovery.locator.enabled: true # автообнаружение сервисов
      routes:

        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: auth-service-internal
          uri: lb://auth-service
          predicates:
            - Path=/internal/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO


management:
  endpoints:
    web:
      exposure:
        include: "env,health,metrics"