spring:
  cloud:
    gateway:
      discovery.locator.enabled: true # автообнаружение сервисов
      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
              - Path=/api/auth/**


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO


management:
  endpoints:
    web:
      exposure:
        include: "env,health,metrics"